# Learn more: https://goreleaser.com
version: 1
builds:
  - env:
      - CGO_ENABLED=1
    flags:
      - -tags=osusergo,netgo,cgo
      - -ldflags=-w -s -extldflags=-static
    tags:
      - osusergo
      - netgo 
      - cgo
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      pre: |
        if [ "{{.Os}}" = "linux" ]; then
          sudo apt-get update && sudo apt-get install -y libsqlite3-dev
        elif [ "{{.Os}}" = "darwin" ]; then
          export PATH="$PATH:/opt/homebrew/bin"
          brew install sqlite
        fi
    main: ./cmd/app/main.go
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: parta

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

release:
  github:
    owner: seqyuan
    name: parta
