# Learn more: https://goreleaser.com
version: 1
builds:
  - id: "linux"
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-I/usr/include
      - CGO_LDFLAGS=-L/usr/lib/x86_64-linux-gnu -lsqlite3
      - PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
    flags:
      - "-tags=cgo,sqlite_omit_load_extension"
    tags:
      - cgo
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    hooks:
      pre:
        - cmd: sudo apt-get update -y
        - cmd: sudo apt-get install -y --no-install-recommends libsqlite3-dev pkg-config
        - cmd: sudo ldconfig
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/app/main.go
    binary: parta

archives:
  - name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: linux
        format: tar.gz

checksum:
  name_template: "{{.ProjectName}}_{{.Version}}_checksums.txt"
  algorithm: sha256

release:
  github:
    owner: seqyuan
    name: parta