# Learn more: https://goreleaser.com
version: 1
builds:
  - id: "linux"
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-I/usr/include
      - CGO_LDFLAGS=-L/usr/lib/x86_64-linux-gnu -lsqlite3
      - PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
    flags:
      - "-tags=cgo,sqlite_omit_load_extension"
    tags:
      - cgo
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}'
    hooks:
      pre:
        - sh -c "set -ex
          # 等待apt锁释放
          while fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do sleep 1; done
          
          cd /tmp
          sudo -E apt-get update -y -qq
          sudo -E apt-get install -y --no-install-recommends libsqlite3-dev pkg-config
          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
          sudo -E ldconfig
          dpkg -L libsqlite3-dev
          # 清理缓存
          sudo -E apt-get clean"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/app/main.go
    binary: parta

archives:
  - name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: linux
        format: tar.gz

checksum:
  name_template: "{{.ProjectName}}_{{.Version}}_checksums.txt"
  algorithm: sha256

release:
  github:
    owner: seqyuan
    name: parta
