# Learn more: https://goreleaser.com
version: 1
builds:
  - env:
      - CGO_ENABLED=1
    flags:
      - -tags=cgo
      - -ldflags=-w -s
    tags:
      - cgo
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      - cmd: sudo apt-get update && sudo apt-get install -y libsqlite3-dev
        dir: /tmp
        platforms: [linux]
      
      - cmd: |
          export PATH="$PATH:/opt/homebrew/bin"
          brew install sqlite
        dir: /tmp  
        platforms: [darwin]
      
    main: ./cmd/app/main.go
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: parta

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

release:
  github:
    owner: seqyuan
    name: parta
